jdk:
  - openjdk8

scala:
  - 2.12.10

services:
  - docker

before_script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - ./sbt clean compile

after_success:
  - ./sbt docker:publish

# blacklist
branches:
  except:
    - RELEASE

notifications:
  slack: sdkman:QdA1XVUuYDjlYL4Z7gm16OEc
