services:
  - docker
env:
  - TERM=dumb
jdk:
  - openjdk8
before_script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker run --rm -d -p="27017:27017" --name=mongo mongo:3.2
  - docker run --rm -d -p "3025:3025" -p "3143:3143" --name greenmail greenmail/standalone:1.5.7
  - docker run --rm -d -p "8080:8080" --name wiremock rodolpheche/wiremock
script:
  - ./gradlew clean -Prelease.useLastTag=true final docker dockerTag dockerPush
after_script:
  - docker rm -f mongo wiremock greenmail
cache:
  directories:
  - "$HOME/.gradle"
branches:
  except:
    - master

