services:
  - docker
env:
  - TERM=dumb
jdk:
  - openjdk8
script:
  - ./gradlew -Prelease.useLastTag=true final docker dockerTag dockerPush
cache:
  directories:
  - "$HOME/.gradle"
branches:
  only:
    - master

