script: "./gradlew clean generateSite"
jdk:
- openjdk8
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  branch: master
  local_dir: site/build/site
  repo: sdkman/beta.sdkman.github.io
