script: "./gradlew generateSite"
jdk:
- openjdk7
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
  local_dir: site/build/site
  repo: sdkman/beta.sdkman.github.io
