name: Release
on:
  push:
    branches:
      - master

jobs:
  build:
    name: "Release"
    runs-on: ubuntu-latest
    environment: production
    services:
      mongodb:
        image: mongo:3.2
        ports:
          - 27017:27017
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_TOKEN }}
    - name: Log in to DigitalOcean Docker Registry
      run: |
        doctl registry login
    - name: Publish local Docker image
      run: ./sbt docker:publishLocal
    - name: Push image to DO registry
      run: |
        version=$(sbt version | tail -n 1 | awk -F ' ' '{print $2}')
        docker push registry.digitalocean.com/sdkman/sdkman-website:$version
        docker push registry.digitalocean.com/sdkman/sdkman-website:latest

